version: '3.0'

services:
  grafana:
    container_name: 'grafana-dev-wildgraphql'
    platform: 'linux/amd64'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-oss}
        # https://grafana.com/docs/grafana/latest/whatsnew/
        grafana_version: ${GRAFANA_VERSION:-10.2.3}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/retrodaredevil-wildgraphql-datasource
      - ./provisioning:/etc/grafana/provisioning
